---
- name: touch files test
  hosts: target
  remote_user: root
  tasks:
  - name: create directory
    file:
      path: /home/worker/test
      state: directory

  - name: touch file
    file:
      path: /home/worker/test/test.txt
      state: touch
